"""Talk to Joey. Your message becomes a clean [BOS] prompt [EOS] prefix; the
response region is generated by iterative unmasking."""
import os
import re
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import torch
from joey.config import MASK_ID, BOS_ID, EOS_ID
from joey.tokenizer import JoeyTokenizer
from joey.train import load_ckpt
from joey.sampler import generate

CKPT = os.environ.get("JOEY_CKPT", "artifacts/joey_chat.pt")


def clean(text):
    """Repair the no-leading-space token artifact (e.g. 'sorryYour' -> 'sorry Your'):
    insert a space where a letter/punctuation is glued to a capital letter."""
    text = re.sub(r"([a-z0-9.,!?;:'])([A-Z])", r"\1 \2", text)
    return re.sub(r"\s+", " ", text).strip()


def main():
    tok = JoeyTokenizer.load("artifacts/tok.json")
    model, cfg, _ = load_ckpt(CKPT, use_ema=True)
    dev = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(dev).eval()
    print(f"Joey ready ({CKPT}). Type 'quit' to exit.")
    while True:
        try:
            msg = input("you> ")
        except (EOFError, KeyboardInterrupt):
            break
        if msg.strip() in ("quit", "exit"):
            break
        prompt = torch.tensor([[BOS_ID] + tok.encode(msg) + [EOS_ID]])
        total = min(cfg.ctx_len, prompt.shape[1] + 40)   # short reply window
        out = generate(model, length=total, steps=96, mask_id=MASK_ID,
                       vocab_size=cfg.vocab_size, prompt_ids=prompt, device=dev,
                       rep_penalty=1.4, top_p=0.85)
        resp = out[0, prompt.shape[1]:].tolist()
        if EOS_ID in resp:                               # stop at end-of-turn
            resp = resp[:resp.index(EOS_ID)]
        print("joey>", clean(tok.decode(resp)))


if __name__ == "__main__":
    main()
