"""Talk to Joey. Your message becomes a clean [BOS] prompt [EOS] prefix; the
response region is generated by iterative unmasking."""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import torch
from joey.config import MASK_ID, BOS_ID, EOS_ID
from joey.tokenizer import JoeyTokenizer
from joey.train import load_ckpt
from joey.sampler import generate

CKPT = os.environ.get("JOEY_CKPT", "artifacts/joey_chat.pt")


def main():
    tok = JoeyTokenizer.load("artifacts/tok.json")
    model, cfg, _ = load_ckpt(CKPT, use_ema=True)
    dev = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(dev).eval()
    print(f"Joey ready ({CKPT}). Type 'quit' to exit.")
    while True:
        try:
            msg = input("you> ")
        except (EOFError, KeyboardInterrupt):
            break
        if msg.strip() in ("quit", "exit"):
            break
        prompt = torch.tensor([[BOS_ID] + tok.encode(msg) + [EOS_ID]])
        out = generate(model, length=cfg.ctx_len, steps=128, mask_id=MASK_ID,
                       vocab_size=cfg.vocab_size, prompt_ids=prompt, device=dev,
                       rep_penalty=1.3, top_p=0.9)
        resp = out[0, prompt.shape[1]:].tolist()
        print("joey>", tok.decode(resp))


if __name__ == "__main__":
    main()
